### ISSUE TITLE
[cob4_base][ros_canopen][cob_elmo_homing] Debugging cob4_base performance

### ISSUE THREAD

**Issue by fmessmer** [4am-robotics/cob_control#98]
Initial assumption:
cob4-base seems to behave "jerkier" since recently. This _could_ be related to switching to `ros_canopen`, but is not guaranteed to be the reason as the behavior has not been monitored in such detail before...so no comparable plots are available.

Creating this issue to document the progress and the insights.
@ipa-mdl @ipa-fmw @ipa-tif @ipa-bnm

(Setup is latest `ros_canopen` (as of https://github.com/ros-industrial/ros_canopen/commit/e513abc12cea620ab32b058bc90252a0e10ada97) and latest "ipa320/indigo_dev" (as of today))

**Comment by fmessmer** [comment]
First experiment on `cob4-1`, commanding the base in `linear/x` direction via joystick show the following command-vs-odometry-plot:

![base_jerkyness](https://cloud.githubusercontent.com/assets/508006/13524522/f8cd8c1a-e1fb-11e5-8449-3d8f793e648f.png)

It can be seen that the `angular/z` odometry increases significantly when moving in `linear/x` direction!

**Comment by fmessmer** [comment]
Applying https://github.com/ipa320/cob_robots/pull/441 does not seem to help much:

![base_jerkyness_20ms](https://cloud.githubusercontent.com/assets/508006/13524693/175d17bc-e1fd-11e5-8fd2-ae19170b92d1.png)

Here are the according `joint_states/velocity`:

![base_jerkyness_20ms_joint_vel](https://cloud.githubusercontent.com/assets/508006/13524793/aac51d6a-e1fd-11e5-9a9e-62bbd2cfaca6.png)

**Comment by fmessmer** [comment]
Applying the following [filter](https://github.com/ros-industrial/ros_canopen/pull/168):

```
sync:
  interval_ms: 20
  overflow: 0
heartbeat:
  rate: 20
  msg: "77f#05"

defaults:
  eds_pkg: cob_hardware_config
  eds_file: "common/ElmoSimplIQ.dcf"
  dcf_overlay:
    "607F": "240000" # max profile velocity
    "6083": "1000000" # profile acceleration
    "6084": "1000000" # profile deceleration
    "6085": "1000000" # quick stop deceleration
  motor_allocator: cob_elmo_homing::ElmoMotor402::Allocator
  motor_layer:
    monitor_mode: false
  velocity_filters:
    - type: filters/MeanFilterDouble
      name: my_filter
      params:
        number_of_observations: 3

drive_wheel: &drive_wheel
  dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
  #  "6098": "35" # homing method
    "607Bsub1": "-1290240000" # min position range limit XM[1]
    "607Bsub2": "1290240000" # max position range limit XM[2]
    "607Dsub1": "-1290240000" # min position software limit VL[3]
    "607Dsub2": "1290240000" # max position software limit VH[3]
  pos_to_device: "rint(pos * 4096 * 21 * 1 / (2 * pi))" # rev * gear * belt / (2 * pi)
  vel_to_device: "rint(vel * 4096 * 21 * 1 / (2 * pi))" # rev * gear * belt / (2 * pi)
  pos_from_device: "obj6064 * 2 * pi / ( 4096 * 21 * 1)" # 2 * pi / (rev * gear * belt)
  vel_from_device: "obj606c * 2 * pi / ( 4096 * 21 * 1)" # 2 * pi / (rev * gear * belt)
  motor_layer:
   homing_event: 0 # -> digin
   homing_speed: 0
   homing_offset: 0

steer_wheel: &steer_wheel
  dcf_overlay:
    "607Bsub1": "-480000000" # min position range limit XM[1]
    "607Bsub2": "480000000" # max position range limit XM[2]
    "607Dsub1": "-480000000" # min position software limit VL[3]
    "607Dsub2": "480000000" # max position software limit VH[3]
  pos_to_device: "rint(pos * 8000 * 1 * 4 / (2 * pi))" # rev * gear * belt / (2 * pi)
  vel_to_device: "rint(vel * 8000 * 1 * 4 / (2 * pi))" # rev * gear * belt / (2 * pi)
  pos_from_device: "obj6064 * 2 * pi / ( 8000 * 1 * 4)" # 2 * pi / (rev * gear * belt)
  vel_from_device: "obj606c * 2 * pi / ( 8000 * 1 * 4)" # 2 * pi / (rev * gear * belt)

nodes:
  ##Wheel 1
  fl_caster_rotation_joint:
    <<: *steer_wheel
    id: 1
    motor_layer:
      homing_event: 19 # -> digin
      homing_speed: -5093 # -1.0 rs/s
      homing_offset: 5551
  fl_caster_r_wheel_joint:
    <<: *drive_wheel
    id: 2

  ##Wheel 2
  b_caster_rotation_joint:
    <<: *steer_wheel
    id: 3
    motor_layer:
      homing_event: 19 # -> digin
      homing_speed: -5093 # -1.0 rs/s
      homing_offset: -15880
  b_caster_r_wheel_joint:
    <<: *drive_wheel
    id: 4

  ##Wheel 3
  fr_caster_rotation_joint:
    <<: *steer_wheel
    id: 5
    motor_layer:
      homing_event: 19 # -> digin
      homing_speed: -5093 # -1.0 rs/s
      homing_offset: -5194
  fr_caster_r_wheel_joint:
    <<: *drive_wheel
    id: 6
```

results in command-vs-odometry:

![base_jerkyness_20ms_filtered](https://cloud.githubusercontent.com/assets/508006/13524930/5776d242-e1fe-11e5-8a1f-647f413720b3.png)

and joint velocities:

![base_jerkyness_20ms_joint_vel_filtered](https://cloud.githubusercontent.com/assets/508006/13524936/5ed6e0e0-e1fe-11e5-912a-24ee59118336.png)
